### PR TITLE
Update SMC bootloader tools

### PR DESCRIPTION
**Pull request by stople**
This PR updates the SMC bootloader tools and information. This is mostly to include changes made in the zip version added here https://github.com/X16Community/x16-smc/pull/53#issuecomment-2362330198 , but, the instructions are also reorganized and cleaned up a bit.

Main changes are that these tools are better together with bootloader v3, and, they add a warning if the user attempts to e.g. install bootloader v2 if bootloader v3 is installed, causing a significant risk of bricking the x16.

Also, I took the liberty to add the pre-built bootloader .BIN files from existing bootloaders to this repo, causing that files are in one place, and that there are fewer risks involved with e.g. renaming the files.

### CODE REVIEW

**Comment by stople** [comment]
@stefan-b-jakobsson ready for review. I did a quick test on my machine, seems like the tools still works.

**Comment by stefan-b-jakobsson** [comment]
There's a dead link to the Flash manipulation tools in doc/update-guide.md under heading "In-system update of the bootloader".

**Comment by stefan-b-jakobsson** [comment]
I tested the new flash tools. They work fine as far as I can tell. I also tested to do an SMC update after updating the bootloader.

One small thing I think I remember from some discussion. The dump tool prints the command you can use to save the bootloader to disk. If I remember correctly, the end address should be the actual end address + 1.

**Comment by stople** [comment]
> There's a dead link to the Flash manipulation tools in doc/update-guide.md under heading "In-system update of the bootloader".

Well spotted. Fixed.

**Comment by stople** [comment]
> I tested the new flash tools. They work fine as far as I can tell. I also tested to do an SMC update after updating the bootloader.
> 
> One small thing I think I remember from some discussion. The dump tool prints the command you can use to save the bootloader to disk. If I remember correctly, the end address should be the actual end address + 1.

I have updated the BSAVE commands to include the last byte

**Comment by stefan-b-jakobsson** [comment]
I think there's still a dead link in update-guide.md, at line 124. It refers to the file flash-manipulation.md that has been renamed.

**Comment by stople** [comment]
Well spotted, again. Fixed.

**Pull request merged**
