### PR TITLE
Adding Eirik's flash tools

### PR DESCRIPTION
**Pull request by stefan-b-jakobsson**
This PR adds Eirik's flash manipulation tools to the SMC project.

Merging this PR requires that Eirik approves that the code is distributed here.

### CODE REVIEW

**Comment by stefan-b-jakobsson** [comment]
@stople Can you comment here that you approve that your code is included in the project.

**Comment by stople** [comment]
> @stople Can you comment here that you approve that your code is included in the project.

Thumbs up from me. I also like that you added them in ascii format (BAS), making the source code easier to read outside Basic.

**Comment by stople** [comment]
By the way, my last name is Stople, not Stolpe 😁

**Comment by stefan-b-jakobsson** [comment]
Last name sorted. Sorry about that.

This PR is ready to be merged. The Github action build currently fails, waiting for PR #48 to be merged, not related to this code.

**Review by mooinglemur — APPROVED** [review]

**Pull request merged**
